apiVersion: v1
kind: Pod
metadata:
  name: etcd
spec:
  hostNetwork: true
  containers:
  - name: etcd1
    image: elcolio/etcd
    args:
    - --name=etcd0
    - --listen-peer-urls=http://192.168.33.10:2380
    - --listen-client-urls=http://0.0.0.0:2379
    - --advertise-client-urls=http://192.168.33.10:2379
    - --initial-advertise-peer-urls=http://192.168.33.10:2380
    - --initial-cluster=etcd0=http://192.168.33.10:2380,etcd1=http://192.168.33.11:2380,etcd2=http://192.168.33.12:2380
    - --initial-cluster-state=new
    - --initial-cluster-token etcd-cluster-100
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - hostPath:
      path: /data/etcd
    name: data
