apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v11
  #namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v11
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v11
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v11
    spec:
      containers:
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.14
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 50Mi
        #livenessProbe:
          #httpGet:
            #path: /healthz
            #port: 8080
            #scheme: HTTP
          #initialDelaySeconds: 60
          #timeoutSeconds: 5
          #successThreshold: 1
          #failureThreshold: 5
        #readinessProbe:
          #httpGet:
            #path: /readiness
            #port: 8081
            #scheme: HTTP
          #initialDelaySeconds: 30
          #timeoutSeconds: 5
        command:
        - /kube2sky
        - --domain="cumulo"
        - --etcd-server="http://192.168.33.100:2379"
        - --kube-master-url="http://192.168.33.100:2379"
      - name: skydns
        image: skynetservices/skydns
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 50Mi
        command: 
        - /skydns
        - -machines=http://192.168.33.100
        - -discover
        - -addr=0.0.0.0:53
        - -domain=cumulo.
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      #- name: healthz
        #image: gcr.io/google_containers/exechealthz:1.0
        #resources:
          #limits:
            #cpu: 10m
            #memory: 20Mi
          #requests:
            #cpu: 10m
            #memory: 20Mi
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: Default  # Don't use cluster DNS.
