--- 
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec: 
  containers: 
    env: 
      - 
        name: NGINX_PORT
        value: 8080
    image: nginx
    name: nginx
    ports: 
      - 
        containerPort: 8080
  hostNetwork: true
